### ISSUE TITLE
Carry Flag wrong comparison

### ISSUE THREAD

**Issue by x86asmr** [bitdefender/bddisasm#39]
```
in bdshemu.c#423

// Set CF.
if ((FM_SUB == FlagsMode) && (Src1 < Src2))
```

should be 

```
// Set CF.
if ((FM_SUB == FlagsMode) && (Src1 < Dst))
```

instead

**Comment by vlutas** [comment]
Indeed, there was a problem (in fact, several problems) on rflags setting. Due to an error in the SET_FLAGS macro, *src* was passed instead of *src1* to the *ShemuSetFlags*, thus wrongly setting the flags. This issue is fixed in the latest commit. 
Note than now, since the first and second sources are passed properly, the *Src1 < Src2* condition becomes correct for *SUB*.

**Comment by x86asmr** [comment]
the latest commit did not fix the issue.

please consider this example:

```
mov rax, 100
mov rdx, 600
cmp rax, rdx
ja bad_jmp
mov rbx, rdx
bad_jmp:
mov rcx, r8
```

`{ 0x48, 0xC7, 0xC0, 0x64, 0x00, 0x00, 0x00, 0x48, 0xC7, 0xC2, 0x58, 0x02, 0x00, 0x00, 0x48, 0x39, 0xD0, 0x77, 0x03, 0x48, 0x89, 0xD3, 0x4C, 0x89, 0xC1 } `

in my test, it will produce the following output and take the branch:

`        RAX = 0x0000000000000000 RCX = 0x0000000000000000 RDX = 0x0000000000000000 RBX = 0x0000000000000000
        RSP = 0x0000000000101000 RBP = 0x0000000000000000 RSI = 0x0000000000000000 RDI = 0x0000000000000000
        R8  = 0x0000000000000000 R9  = 0x0000000000000000 R10 = 0x0000000000000000 R11 = 0x0000000000000000
        R12 = 0x0000000000000000 R13 = 0x0000000000000000 R14 = 0x0000000000000000 R15 = 0x0000000000000000
        RIP = 0x00007ff68e68bb60 RFLAGS = 0x0000000000000202
Emulating: 0x00007ff68e68bb60 MOV       rax, 0x000000000000007b
        RAX = 0x000000000000007b RCX = 0x0000000000000000 RDX = 0x0000000000000000 RBX = 0x0000000000000000
        RSP = 0x0000000000101000 RBP = 0x0000000000000000 RSI = 0x0000000000000000 RDI = 0x0000000000000000
        R8  = 0x0000000000000000 R9  = 0x0000000000000000 R10 = 0x0000000000000000 R11 = 0x0000000000000000
        R12 = 0x0000000000000000 R13 = 0x0000000000000000 R14 = 0x0000000000000000 R15 = 0x0000000000000000
        RIP = 0x00007ff68e68bb67 RFLAGS = 0x0000000000000202
Emulating: 0x00007ff68e68bb67 MOV       rdx, 0x00000000000000ea
        RAX = 0x000000000000007b RCX = 0x0000000000000000 RDX = 0x00000000000000ea RBX = 0x0000000000000000
        RSP = 0x0000000000101000 RBP = 0x0000000000000000 RSI = 0x0000000000000000 RDI = 0x0000000000000000
        R8  = 0x0000000000000000 R9  = 0x0000000000000000 R10 = 0x0000000000000000 R11 = 0x0000000000000000
        R12 = 0x0000000000000000 R13 = 0x0000000000000000 R14 = 0x0000000000000000 R15 = 0x0000000000000000
        RIP = 0x00007ff68e68bb6e RFLAGS = 0x0000000000000202
Emulating: 0x00007ff68e68bb6e CMP       rax, rdx
        RAX = 0x000000000000007b RCX = 0x0000000000000000 RDX = 0x00000000000000ea RBX = 0x0000000000000000
        RSP = 0x0000000000101000 RBP = 0x0000000000000000 RSI = 0x0000000000000000 RDI = 0x0000000000000000
        R8  = 0x0000000000000000 R9  = 0x0000000000000000 R10 = 0x0000000000000000 R11 = 0x0000000000000000
        R12 = 0x0000000000000000 R13 = 0x0000000000000000 R14 = 0x0000000000000000 R15 = 0x0000000000000000
        RIP = 0x00007ff68e68bb71 RFLAGS = 0x0000000000000282
Emulating: 0x00007ff68e68bb71 JNBE      0x7ff68e68bb76
        RAX = 0x000000000000007b RCX = 0x0000000000000000 RDX = 0x00000000000000ea RBX = 0x0000000000000000
        RSP = 0x0000000000101000 RBP = 0x0000000000000000 RSI = 0x0000000000000000 RDI = 0x0000000000000000
        R8  = 0x0000000000000000 R9  = 0x0000000000000000 R10 = 0x0000000000000000 R11 = 0x0000000000000000
        R12 = 0x0000000000000000 R13 = 0x0000000000000000 R14 = 0x0000000000000000 R15 = 0x0000000000000000
        RIP = 0x00007ff68e68bb76 RFLAGS = 0x0000000000000282
Emulating: 0x00007ff68e68bb76 MOV       rcx, r8
        RAX = 0x000000000000007b RCX = 0x0000000000000000 RDX = 0x00000000000000ea RBX = 0x0000000000000000
        RSP = 0x0000000000101000 RBP = 0x0000000000000000 RSI = 0x0000000000000000 RDI = 0x0000000000000000
        R8  = 0x0000000000000000 R9  = 0x0000000000000000 R10 = 0x0000000000000000 R11 = 0x0000000000000000
        R12 = 0x0000000000000000 R13 = 0x0000000000000000 R14 = 0x0000000000000000 R15 = 0x0000000000000000
        RIP = 0x00007ff68e68bb79 RFLAGS = 0x0000000000000282`

**Comment by x86asmr** [comment]
oh yes i see now
